package netty.appFramework.netty.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtofulRequeset.proto

public final class ProtoRequest {
  private ProtoRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .UserLogin userLogin = 1;</code>
     */
    ProtoRequest.UserLogin getUserLogin();
    /**
     * <code>optional .UserLogin userLogin = 1;</code>
     */
    ProtoRequest.UserLoginOrBuilder getUserLoginOrBuilder();

    /**
     * <code>optional .UserLogOut userLogOut = 2;</code>
     */
    ProtoRequest.UserLogOut getUserLogOut();
    /**
     * <code>optional .UserLogOut userLogOut = 2;</code>
     */
    ProtoRequest.UserLogOutOrBuilder getUserLogOutOrBuilder();

    public ProtoRequest.Request.CommandCase getCommandCase();
  }
  /**
   * Protobuf type {@code Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Request() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ProtoRequest.UserLogin.Builder subBuilder = null;
              if (commandCase_ == 1) {
                subBuilder = ((ProtoRequest.UserLogin) command_).toBuilder();
              }
              command_ =
                  input.readMessage(ProtoRequest.UserLogin.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ProtoRequest.UserLogin) command_);
                command_ = subBuilder.buildPartial();
              }
              commandCase_ = 1;
              break;
            }
            case 18: {
              ProtoRequest.UserLogOut.Builder subBuilder = null;
              if (commandCase_ == 2) {
                subBuilder = ((ProtoRequest.UserLogOut) command_).toBuilder();
              }
              command_ =
                  input.readMessage(ProtoRequest.UserLogOut.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ProtoRequest.UserLogOut) command_);
                command_ = subBuilder.buildPartial();
              }
              commandCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoRequest.internal_static_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoRequest.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoRequest.Request.class, ProtoRequest.Request.Builder.class);
    }

    private int commandCase_ = 0;
    private java.lang.Object command_;
    public enum CommandCase
        implements com.google.protobuf.Internal.EnumLite {
      USERLOGIN(1),
      USERLOGOUT(2),
      COMMAND_NOT_SET(0);
      private int value = 0;
      private CommandCase(int value) {
        this.value = value;
      }
      public static CommandCase valueOf(int value) {
        switch (value) {
          case 1: return USERLOGIN;
          case 2: return USERLOGOUT;
          case 0: return COMMAND_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public CommandCase
    getCommandCase() {
      return CommandCase.valueOf(
          commandCase_);
    }

    public static final int USERLOGIN_FIELD_NUMBER = 1;
    /**
     * <code>optional .UserLogin userLogin = 1;</code>
     */
    public ProtoRequest.UserLogin getUserLogin() {
      if (commandCase_ == 1) {
         return (ProtoRequest.UserLogin) command_;
      }
      return ProtoRequest.UserLogin.getDefaultInstance();
    }
    /**
     * <code>optional .UserLogin userLogin = 1;</code>
     */
    public ProtoRequest.UserLoginOrBuilder getUserLoginOrBuilder() {
      if (commandCase_ == 1) {
         return (ProtoRequest.UserLogin) command_;
      }
      return ProtoRequest.UserLogin.getDefaultInstance();
    }

    public static final int USERLOGOUT_FIELD_NUMBER = 2;
    /**
     * <code>optional .UserLogOut userLogOut = 2;</code>
     */
    public ProtoRequest.UserLogOut getUserLogOut() {
      if (commandCase_ == 2) {
         return (ProtoRequest.UserLogOut) command_;
      }
      return ProtoRequest.UserLogOut.getDefaultInstance();
    }
    /**
     * <code>optional .UserLogOut userLogOut = 2;</code>
     */
    public ProtoRequest.UserLogOutOrBuilder getUserLogOutOrBuilder() {
      if (commandCase_ == 2) {
         return (ProtoRequest.UserLogOut) command_;
      }
      return ProtoRequest.UserLogOut.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commandCase_ == 1) {
        output.writeMessage(1, (ProtoRequest.UserLogin) command_);
      }
      if (commandCase_ == 2) {
        output.writeMessage(2, (ProtoRequest.UserLogOut) command_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commandCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (ProtoRequest.UserLogin) command_);
      }
      if (commandCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (ProtoRequest.UserLogOut) command_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static ProtoRequest.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoRequest.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoRequest.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoRequest.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoRequest.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoRequest.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoRequest.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoRequest.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoRequest.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoRequest.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoRequest.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        ProtoRequest.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoRequest.internal_static_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoRequest.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoRequest.Request.class, ProtoRequest.Request.Builder.class);
      }

      // Construct using ProtoRequest.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        commandCase_ = 0;
        command_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoRequest.internal_static_Request_descriptor;
      }

      public ProtoRequest.Request getDefaultInstanceForType() {
        return ProtoRequest.Request.getDefaultInstance();
      }

      public ProtoRequest.Request build() {
        ProtoRequest.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoRequest.Request buildPartial() {
        ProtoRequest.Request result = new ProtoRequest.Request(this);
        if (commandCase_ == 1) {
          if (userLoginBuilder_ == null) {
            result.command_ = command_;
          } else {
            result.command_ = userLoginBuilder_.build();
          }
        }
        if (commandCase_ == 2) {
          if (userLogOutBuilder_ == null) {
            result.command_ = command_;
          } else {
            result.command_ = userLogOutBuilder_.build();
          }
        }
        result.commandCase_ = commandCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoRequest.Request) {
          return mergeFrom((ProtoRequest.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoRequest.Request other) {
        if (other == ProtoRequest.Request.getDefaultInstance()) return this;
        switch (other.getCommandCase()) {
          case USERLOGIN: {
            mergeUserLogin(other.getUserLogin());
            break;
          }
          case USERLOGOUT: {
            mergeUserLogOut(other.getUserLogOut());
            break;
          }
          case COMMAND_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoRequest.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoRequest.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int commandCase_ = 0;
      private java.lang.Object command_;
      public CommandCase
          getCommandCase() {
        return CommandCase.valueOf(
            commandCase_);
      }

      public Builder clearCommand() {
        commandCase_ = 0;
        command_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilder<
          ProtoRequest.UserLogin, ProtoRequest.UserLogin.Builder, ProtoRequest.UserLoginOrBuilder> userLoginBuilder_;
      /**
       * <code>optional .UserLogin userLogin = 1;</code>
       */
      public ProtoRequest.UserLogin getUserLogin() {
        if (userLoginBuilder_ == null) {
          if (commandCase_ == 1) {
            return (ProtoRequest.UserLogin) command_;
          }
          return ProtoRequest.UserLogin.getDefaultInstance();
        } else {
          if (commandCase_ == 1) {
            return userLoginBuilder_.getMessage();
          }
          return ProtoRequest.UserLogin.getDefaultInstance();
        }
      }
      /**
       * <code>optional .UserLogin userLogin = 1;</code>
       */
      public Builder setUserLogin(ProtoRequest.UserLogin value) {
        if (userLoginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          command_ = value;
          onChanged();
        } else {
          userLoginBuilder_.setMessage(value);
        }
        commandCase_ = 1;
        return this;
      }
      /**
       * <code>optional .UserLogin userLogin = 1;</code>
       */
      public Builder setUserLogin(
          ProtoRequest.UserLogin.Builder builderForValue) {
        if (userLoginBuilder_ == null) {
          command_ = builderForValue.build();
          onChanged();
        } else {
          userLoginBuilder_.setMessage(builderForValue.build());
        }
        commandCase_ = 1;
        return this;
      }
      /**
       * <code>optional .UserLogin userLogin = 1;</code>
       */
      public Builder mergeUserLogin(ProtoRequest.UserLogin value) {
        if (userLoginBuilder_ == null) {
          if (commandCase_ == 1 &&
              command_ != ProtoRequest.UserLogin.getDefaultInstance()) {
            command_ = ProtoRequest.UserLogin.newBuilder((ProtoRequest.UserLogin) command_)
                .mergeFrom(value).buildPartial();
          } else {
            command_ = value;
          }
          onChanged();
        } else {
          if (commandCase_ == 1) {
            userLoginBuilder_.mergeFrom(value);
          }
          userLoginBuilder_.setMessage(value);
        }
        commandCase_ = 1;
        return this;
      }
      /**
       * <code>optional .UserLogin userLogin = 1;</code>
       */
      public Builder clearUserLogin() {
        if (userLoginBuilder_ == null) {
          if (commandCase_ == 1) {
            commandCase_ = 0;
            command_ = null;
            onChanged();
          }
        } else {
          if (commandCase_ == 1) {
            commandCase_ = 0;
            command_ = null;
          }
          userLoginBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .UserLogin userLogin = 1;</code>
       */
      public ProtoRequest.UserLogin.Builder getUserLoginBuilder() {
        return getUserLoginFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .UserLogin userLogin = 1;</code>
       */
      public ProtoRequest.UserLoginOrBuilder getUserLoginOrBuilder() {
        if ((commandCase_ == 1) && (userLoginBuilder_ != null)) {
          return userLoginBuilder_.getMessageOrBuilder();
        } else {
          if (commandCase_ == 1) {
            return (ProtoRequest.UserLogin) command_;
          }
          return ProtoRequest.UserLogin.getDefaultInstance();
        }
      }
      /**
       * <code>optional .UserLogin userLogin = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ProtoRequest.UserLogin, ProtoRequest.UserLogin.Builder, ProtoRequest.UserLoginOrBuilder> 
          getUserLoginFieldBuilder() {
        if (userLoginBuilder_ == null) {
          if (!(commandCase_ == 1)) {
            command_ = ProtoRequest.UserLogin.getDefaultInstance();
          }
          userLoginBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ProtoRequest.UserLogin, ProtoRequest.UserLogin.Builder, ProtoRequest.UserLoginOrBuilder>(
                  (ProtoRequest.UserLogin) command_,
                  getParentForChildren(),
                  isClean());
          command_ = null;
        }
        commandCase_ = 1;
        onChanged();;
        return userLoginBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          ProtoRequest.UserLogOut, ProtoRequest.UserLogOut.Builder, ProtoRequest.UserLogOutOrBuilder> userLogOutBuilder_;
      /**
       * <code>optional .UserLogOut userLogOut = 2;</code>
       */
      public ProtoRequest.UserLogOut getUserLogOut() {
        if (userLogOutBuilder_ == null) {
          if (commandCase_ == 2) {
            return (ProtoRequest.UserLogOut) command_;
          }
          return ProtoRequest.UserLogOut.getDefaultInstance();
        } else {
          if (commandCase_ == 2) {
            return userLogOutBuilder_.getMessage();
          }
          return ProtoRequest.UserLogOut.getDefaultInstance();
        }
      }
      /**
       * <code>optional .UserLogOut userLogOut = 2;</code>
       */
      public Builder setUserLogOut(ProtoRequest.UserLogOut value) {
        if (userLogOutBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          command_ = value;
          onChanged();
        } else {
          userLogOutBuilder_.setMessage(value);
        }
        commandCase_ = 2;
        return this;
      }
      /**
       * <code>optional .UserLogOut userLogOut = 2;</code>
       */
      public Builder setUserLogOut(
          ProtoRequest.UserLogOut.Builder builderForValue) {
        if (userLogOutBuilder_ == null) {
          command_ = builderForValue.build();
          onChanged();
        } else {
          userLogOutBuilder_.setMessage(builderForValue.build());
        }
        commandCase_ = 2;
        return this;
      }
      /**
       * <code>optional .UserLogOut userLogOut = 2;</code>
       */
      public Builder mergeUserLogOut(ProtoRequest.UserLogOut value) {
        if (userLogOutBuilder_ == null) {
          if (commandCase_ == 2 &&
              command_ != ProtoRequest.UserLogOut.getDefaultInstance()) {
            command_ = ProtoRequest.UserLogOut.newBuilder((ProtoRequest.UserLogOut) command_)
                .mergeFrom(value).buildPartial();
          } else {
            command_ = value;
          }
          onChanged();
        } else {
          if (commandCase_ == 2) {
            userLogOutBuilder_.mergeFrom(value);
          }
          userLogOutBuilder_.setMessage(value);
        }
        commandCase_ = 2;
        return this;
      }
      /**
       * <code>optional .UserLogOut userLogOut = 2;</code>
       */
      public Builder clearUserLogOut() {
        if (userLogOutBuilder_ == null) {
          if (commandCase_ == 2) {
            commandCase_ = 0;
            command_ = null;
            onChanged();
          }
        } else {
          if (commandCase_ == 2) {
            commandCase_ = 0;
            command_ = null;
          }
          userLogOutBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .UserLogOut userLogOut = 2;</code>
       */
      public ProtoRequest.UserLogOut.Builder getUserLogOutBuilder() {
        return getUserLogOutFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .UserLogOut userLogOut = 2;</code>
       */
      public ProtoRequest.UserLogOutOrBuilder getUserLogOutOrBuilder() {
        if ((commandCase_ == 2) && (userLogOutBuilder_ != null)) {
          return userLogOutBuilder_.getMessageOrBuilder();
        } else {
          if (commandCase_ == 2) {
            return (ProtoRequest.UserLogOut) command_;
          }
          return ProtoRequest.UserLogOut.getDefaultInstance();
        }
      }
      /**
       * <code>optional .UserLogOut userLogOut = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ProtoRequest.UserLogOut, ProtoRequest.UserLogOut.Builder, ProtoRequest.UserLogOutOrBuilder> 
          getUserLogOutFieldBuilder() {
        if (userLogOutBuilder_ == null) {
          if (!(commandCase_ == 2)) {
            command_ = ProtoRequest.UserLogOut.getDefaultInstance();
          }
          userLogOutBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ProtoRequest.UserLogOut, ProtoRequest.UserLogOut.Builder, ProtoRequest.UserLogOutOrBuilder>(
                  (ProtoRequest.UserLogOut) command_,
                  getParentForChildren(),
                  isClean());
          command_ = null;
        }
        commandCase_ = 2;
        onChanged();;
        return userLogOutBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final ProtoRequest.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoRequest.Request();
    }

    public static ProtoRequest.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Request(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public ProtoRequest.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string reqMap = 1;</code>
     */
    java.lang.String getReqMap();
    /**
     * <code>optional string reqMap = 1;</code>
     */
    com.google.protobuf.ByteString
        getReqMapBytes();
  }
  /**
   * Protobuf type {@code UserLogin}
   */
  public  static final class UserLogin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UserLogin)
      UserLoginOrBuilder {
    // Use UserLogin.newBuilder() to construct.
    private UserLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserLogin() {
      reqMap_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              reqMap_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoRequest.internal_static_UserLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoRequest.internal_static_UserLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoRequest.UserLogin.class, ProtoRequest.UserLogin.Builder.class);
    }

    public static final int REQMAP_FIELD_NUMBER = 1;
    private volatile java.lang.Object reqMap_;
    /**
     * <code>optional string reqMap = 1;</code>
     */
    public java.lang.String getReqMap() {
      java.lang.Object ref = reqMap_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqMap_ = s;
        return s;
      }
    }
    /**
     * <code>optional string reqMap = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReqMapBytes() {
      java.lang.Object ref = reqMap_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqMap_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReqMapBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, reqMap_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReqMapBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, reqMap_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static ProtoRequest.UserLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoRequest.UserLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoRequest.UserLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoRequest.UserLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoRequest.UserLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoRequest.UserLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoRequest.UserLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoRequest.UserLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoRequest.UserLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoRequest.UserLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoRequest.UserLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserLogin)
        ProtoRequest.UserLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoRequest.internal_static_UserLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoRequest.internal_static_UserLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoRequest.UserLogin.class, ProtoRequest.UserLogin.Builder.class);
      }

      // Construct using ProtoRequest.UserLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        reqMap_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoRequest.internal_static_UserLogin_descriptor;
      }

      public ProtoRequest.UserLogin getDefaultInstanceForType() {
        return ProtoRequest.UserLogin.getDefaultInstance();
      }

      public ProtoRequest.UserLogin build() {
        ProtoRequest.UserLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoRequest.UserLogin buildPartial() {
        ProtoRequest.UserLogin result = new ProtoRequest.UserLogin(this);
        result.reqMap_ = reqMap_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoRequest.UserLogin) {
          return mergeFrom((ProtoRequest.UserLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoRequest.UserLogin other) {
        if (other == ProtoRequest.UserLogin.getDefaultInstance()) return this;
        if (!other.getReqMap().isEmpty()) {
          reqMap_ = other.reqMap_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoRequest.UserLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoRequest.UserLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object reqMap_ = "";
      /**
       * <code>optional string reqMap = 1;</code>
       */
      public java.lang.String getReqMap() {
        java.lang.Object ref = reqMap_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqMap_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string reqMap = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReqMapBytes() {
        java.lang.Object ref = reqMap_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqMap_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string reqMap = 1;</code>
       */
      public Builder setReqMap(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqMap_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string reqMap = 1;</code>
       */
      public Builder clearReqMap() {
        
        reqMap_ = getDefaultInstance().getReqMap();
        onChanged();
        return this;
      }
      /**
       * <code>optional string reqMap = 1;</code>
       */
      public Builder setReqMapBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqMap_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UserLogin)
    }

    // @@protoc_insertion_point(class_scope:UserLogin)
    private static final ProtoRequest.UserLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoRequest.UserLogin();
    }

    public static ProtoRequest.UserLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserLogin>
        PARSER = new com.google.protobuf.AbstractParser<UserLogin>() {
      public UserLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new UserLogin(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<UserLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserLogin> getParserForType() {
      return PARSER;
    }

    public ProtoRequest.UserLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserLogOutOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserLogOut)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string reqMap = 1;</code>
     */
    java.lang.String getReqMap();
    /**
     * <code>optional string reqMap = 1;</code>
     */
    com.google.protobuf.ByteString
        getReqMapBytes();
  }
  /**
   * Protobuf type {@code UserLogOut}
   */
  public  static final class UserLogOut extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UserLogOut)
      UserLogOutOrBuilder {
    // Use UserLogOut.newBuilder() to construct.
    private UserLogOut(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserLogOut() {
      reqMap_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserLogOut(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              reqMap_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoRequest.internal_static_UserLogOut_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoRequest.internal_static_UserLogOut_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoRequest.UserLogOut.class, ProtoRequest.UserLogOut.Builder.class);
    }

    public static final int REQMAP_FIELD_NUMBER = 1;
    private volatile java.lang.Object reqMap_;
    /**
     * <code>optional string reqMap = 1;</code>
     */
    public java.lang.String getReqMap() {
      java.lang.Object ref = reqMap_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqMap_ = s;
        return s;
      }
    }
    /**
     * <code>optional string reqMap = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReqMapBytes() {
      java.lang.Object ref = reqMap_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqMap_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReqMapBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, reqMap_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReqMapBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, reqMap_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static ProtoRequest.UserLogOut parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoRequest.UserLogOut parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoRequest.UserLogOut parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoRequest.UserLogOut parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoRequest.UserLogOut parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoRequest.UserLogOut parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoRequest.UserLogOut parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoRequest.UserLogOut parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoRequest.UserLogOut parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoRequest.UserLogOut parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoRequest.UserLogOut prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserLogOut}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserLogOut)
        ProtoRequest.UserLogOutOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoRequest.internal_static_UserLogOut_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoRequest.internal_static_UserLogOut_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoRequest.UserLogOut.class, ProtoRequest.UserLogOut.Builder.class);
      }

      // Construct using ProtoRequest.UserLogOut.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        reqMap_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoRequest.internal_static_UserLogOut_descriptor;
      }

      public ProtoRequest.UserLogOut getDefaultInstanceForType() {
        return ProtoRequest.UserLogOut.getDefaultInstance();
      }

      public ProtoRequest.UserLogOut build() {
        ProtoRequest.UserLogOut result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoRequest.UserLogOut buildPartial() {
        ProtoRequest.UserLogOut result = new ProtoRequest.UserLogOut(this);
        result.reqMap_ = reqMap_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoRequest.UserLogOut) {
          return mergeFrom((ProtoRequest.UserLogOut)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoRequest.UserLogOut other) {
        if (other == ProtoRequest.UserLogOut.getDefaultInstance()) return this;
        if (!other.getReqMap().isEmpty()) {
          reqMap_ = other.reqMap_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoRequest.UserLogOut parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoRequest.UserLogOut) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object reqMap_ = "";
      /**
       * <code>optional string reqMap = 1;</code>
       */
      public java.lang.String getReqMap() {
        java.lang.Object ref = reqMap_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqMap_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string reqMap = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReqMapBytes() {
        java.lang.Object ref = reqMap_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqMap_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string reqMap = 1;</code>
       */
      public Builder setReqMap(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqMap_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string reqMap = 1;</code>
       */
      public Builder clearReqMap() {
        
        reqMap_ = getDefaultInstance().getReqMap();
        onChanged();
        return this;
      }
      /**
       * <code>optional string reqMap = 1;</code>
       */
      public Builder setReqMapBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqMap_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UserLogOut)
    }

    // @@protoc_insertion_point(class_scope:UserLogOut)
    private static final ProtoRequest.UserLogOut DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoRequest.UserLogOut();
    }

    public static ProtoRequest.UserLogOut getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserLogOut>
        PARSER = new com.google.protobuf.AbstractParser<UserLogOut>() {
      public UserLogOut parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new UserLogOut(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<UserLogOut> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserLogOut> getParserForType() {
      return PARSER;
    }

    public ProtoRequest.UserLogOut getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserLogin_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserLogOut_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserLogOut_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ProtofulRequeset.proto\"X\n\007Request\022\037\n\tu" +
      "serLogin\030\001 \001(\0132\n.UserLoginH\000\022!\n\nuserLogO" +
      "ut\030\002 \001(\0132\013.UserLogOutH\000B\t\n\007Command\"\033\n\tUs" +
      "erLogin\022\016\n\006reqMap\030\001 \001(\t\"\034\n\nUserLogOut\022\016\n" +
      "\006reqMap\030\001 \001(\tB\016B\014ProtoRequestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "UserLogin", "UserLogOut", "Command", });
    internal_static_UserLogin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserLogin_descriptor,
        new java.lang.String[] { "ReqMap", });
    internal_static_UserLogOut_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserLogOut_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserLogOut_descriptor,
        new java.lang.String[] { "ReqMap", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
