
package webservice.ws2.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderProcess", targetNamespace = "http://server.ws2.webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderProcess {


    /**
     * 
     * @return
     *     returns java.util.List<webservice.ws2.client.Order>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderList", targetNamespace = "http://server.ws2.webservice/", className = "webservice.ws2.client.GetOrderList")
    @ResponseWrapper(localName = "getOrderListResponse", targetNamespace = "http://server.ws2.webservice/", className = "webservice.ws2.client.GetOrderListResponse")
    public List<Order> getOrderList();

    /**
     * 
     * @return
     *     returns webservice.ws2.client.GetOrderMapResponse.Return
     */
    @WebMethod
    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "getOrderMap", targetNamespace = "http://server.ws2.webservice/", className = "webservice.ws2.client.GetOrderMap")
    @ResponseWrapper(localName = "getOrderMapResponse", targetNamespace = "http://server.ws2.webservice/", className = "webservice.ws2.client.GetOrderMapResponse")
    public webservice.ws2.client.GetOrderMapResponse.Return getOrderMap();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processOrder", targetNamespace = "http://server.ws2.webservice/", className = "webservice.ws2.client.ProcessOrder")
    @ResponseWrapper(localName = "processOrderResponse", targetNamespace = "http://server.ws2.webservice/", className = "webservice.ws2.client.ProcessOrderResponse")
    public String processOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

}
